window.__ATELIER_CFG = {
  ATELIER_SUIVI_PASS_STE:     STEGREVE253695!,
  ATELIER_SUIVI_PASS_BG:      BOURGOIN386548!,
  ATELIER_SUIVI_PASS_LIMITED: DURAND38!,
  ATELIER_SUIVI_PASS_CHASSE:  CHASSE56478!
};
